name: CI

on:
  pull_request:
  push:
  schedule:
    - cron: 0 0 * * 0  # Weekly schedule
  workflow_dispatch:  # Manually trigger the workflow

defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'

jobs:
  test:
    name: Test the Application
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Install dependencies for cross-platform support
      - run: sudo apt-get update && sudo apt-get install -y --no-install-recommends binfmt-support qemu-user-static

      # Run build and test scripts (assuming these scripts are in your repository)
      - run: ./build.sh
      - run: ./test.sh gosu-amd64
      - run: ./test.sh gosu-i386
      - run: ./test.sh --debian gosu-amd64
      - run: ./test.sh --debian gosu-i386

      # Run govulncheck to check for known vulnerabilities in the binaries
      - name: govulncheck
        run: |
          for gosu in gosu-*; do
            ./govulncheck-with-excludes.sh -mode=binary "$gosu"
          done
