name: CI

on:
  pull_request:
  push:
  schedule:
    - cron: 0 0 * * 0  # Weekly schedule
  workflow_dispatch:  # Manually trigger the workflow

defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'

jobs:
  test:
    name: Test the Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Run Python tests
        run: |
          poetry run pytest tests/ --maxfail=1 --disable-warnings -q

